### ISSUE TITLE
代码风格

### ISSUE THREAD

**Issue by yowaimono** [szluyu99/gin-vue-blog#23]
一年多以前看到作者这个项目拉下来跑了一下，很喜欢作者的代码风格，在我心中一直是典范，看着很舒服，现在又重新写Go业务了，于是又来复习一下，但是有些疑问，现在看来项目后端代码量并不算多，是出于这个问题才没有分层吗？我也不喜欢把简单的事情变复杂重构后的代码也依然很整洁清晰，希望可以解答

**Comment by szluyu99** [comment]
三层的分层版本（controller + service + dao）的代码可以看 api-v1 分支（那个版本的代码并不优雅）

main 分支的代码可以理解为只分了两层（handle + model）
- handle 层可以理解为 controller + service 的综合，model 层可以理解为 service + dao 的综合
- 主要是为了开发的更加敏捷，分层多的时候大部分时候还需要思考代码如何架构，心智负担其实很重
- 分层少的时候，可以更专注在业务代码逻辑的编写上

关于项目大小对分层的影响，我也不太确定哪个临界点会让不同分层体检差距较大
- 我认为小项目确实没必要从一开始分层太多，最怕代码还没写几行，先把架构拆个七零八碎
- 代码的架构应该是逐步演变的，当你觉得需要多一层的时候，那应该就是自然而然会多一层

最后就是从语言角度考虑，Golang 的哲学是大道至简，少就是多
- 编码的出发点应该是实现功能的最小实现
- 当功能点变多的时候，应当敏捷地根据实际情况调整架构

**Comment by yowaimono** [comment]
感谢回复，我原来看的是v1的代码，我也觉得小项目用不上复杂的分层架构，但是一只手编码规范的限制，想来自己编码确实怎么舒服怎么来就行，结构清晰就行
