### ISSUE TITLE
windows搭建后怎么访问呀

### ISSUE THREAD

**Issue by DengYuncheng27** [szluyu99/gin-vue-blog#3]
emm，，就是我server, front 都跑起来了 但是感觉缺了个web？没法直接通过浏览器访问。 想问下该怎么访问呢。
![image](https://user-images.githubusercontent.com/56923863/212495248-d6f84556-a81c-4e33-8143-f25abb170245.png)

**Comment by szluyu99** [comment]
没有问题呀，访问  http://localhost:3333 就是前台，http://localhost:3100 就是后台

**Comment by DengYuncheng27** [comment]
> 没有问题呀，访问 http://localhost:3333 就是前台，http://localhost:3100 就是后台

感谢，已解决。
