### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by SaroValentine** [szluyu99/gin-vue-blog#9]
![20231210213206](https://github.com/szluyu99/gin-vue-blog/assets/135717891/f1849409-f0ff-4274-9bcf-10c645c9b3c3)
xiang
![20231210213231](https://github.com/szluyu99/gin-vue-blog/assets/135717891/81b2e701-f910-4f24-af5e-5231af8282d8)
部署完成后打开网页成这样，想问下这个是什么原因造成的，怎么解决，谢谢作者

**Comment by szluyu99** [comment]
你要不要加个群，我 QQ 上给你解答一下

**Comment by SaroValentine** [comment]
找到原因了，在index.html中https和http的锅
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> 
<meta http-equiv="Content-Security-Policy">
